# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  docs:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Checkout gh-pages
        run: git pull && git checkout gh-pages && git merge master

      - name: Install apt packages
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc wine-stable python3-sphinx jupyter
      
      - name: Install pip packages
        run: |
          pip3 install setuptools==49.0.0 wheel
          pip3 install -r requirements.txt
          pip3 install sphinx numpydoc sphinx_rtd_theme sphinx_nbexamples pandoc

      - name: Build the doc
        run: |
          cd docsrc
          python3 -m sphinx -b html . ../docs
          cd ..
        
      - name: List files
        run: ls
        
      - name: Commit docs
        run: |
          git config --global user.name 'Github Action'
          git config --global user.email 'githubAction@users.noreply.github.com'
          git add docs/*
          git commit -am "Automated docs build"
          git push
