# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  docs:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install apt packages
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc wine-stable python3-sphinx jupyter
      
      - name: Install pip packages
        run: |
          pip3 install setuptools==49.0.0 wheel
          pip3 install -r requirements.txt
          pip3 install sphinx numpydoc sphinx_rtd_theme sphinx_nbexamples pandoc

      - name: Build the doc
        run: |
          cd docsrc
          python3 -m sphinx -b html . _build/html
          cd ..
        
      - name: List files
        run: ls
        
      - name: Commit to gh-pages
        run: |
          cd ..
          git clone https://github.com/agrogeophy/notebooks.git --branch gh-pages --single-branch gh-pages
          find ./
          cp -r notebooks/docsrc/_build/html/ gh-pages/docs/
          cd gh-pages
          git config --local user.email "sagitta1618@users.noreply.github.com"
          git config --local user.name "jkl"
          git add docs/*
          git commit -m "Update documentation" -a || true
          git pull
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          branch: gh-pages 
